Repository redhat-documentation/vale-at-red-hat, pull requests merged in 2023-10, with the labels that each got.

#661 No TOC are allowed in OpenShift modules
  .vale/fixtures/OpenShiftAsciiDoc/NoTocInModules/.vale.ini
  .vale/fixtures/OpenShiftAsciiDoc/NoTocInModules/testinvalid.adoc
  .vale/fixtures/OpenShiftAsciiDoc/NoTocInModules/testvalid.adoc
  .vale/styles/OpenShiftAsciiDoc/NoTocInModules.yml
Labels: OpenShiftAsciiDoc

#674 Add "reentrant" to spelling rule
  .vale/fixtures/RedHat/Spelling/testvalid.adoc
  .vale/styles/RedHat/Spelling.yml
Labels: hacktoberfest2023

#675 Add deserialize and variants
  .vale/fixtures/RedHat/Spelling/testvalid.adoc
  .vale/styles/RedHat/Spelling.yml
Labels: hacktoberfest2023

#670 618: Fixing packages in VRH docs procedure
  modules/user-guide/pages/asciidoc-style-for-vale.adoc
  modules/user-guide/pages/openshift-asciidoc-style-for-vale.adoc
Labels: hacktoberfest2023

#682 Fix heading and case-sensitive rule for role-based access control (RBAC)
  .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
  .vale/fixtures/RedHat/Headings/testvalid.adoc
  .vale/styles/RedHat/CaseSensitiveTerms.yml
Labels: bug, hacktoberfest2023

#681 Add valid component names to headings and capitalization rules
  .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
  .vale/fixtures/RedHat/Headings/testvalid.adoc
  .vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc
  .vale/fixtures/RedHat/Spelling/testvalid.adoc
  .vale/styles/RedHat/CaseSensitiveTerms.yml
  .vale/styles/RedHat/Headings.yml
  .vale/styles/RedHat/PascalCamelCase.yml
  .vale/styles/RedHat/Spelling.yml
Labels: bug, hacktoberfest2023

#683 Update installation instructions
  modules/user-guide/pages/installing-vale-cli.adoc
Labels: hacktoberfest2023

#680 Replace the :_content-type: variable with the :_mod-docs-content-type: variable
  .vale/fixtures/AsciiDoc/ClosedAttributeBlocks/testinvalid.adoc
  .vale/fixtures/AsciiDoc/ClosedAttributeBlocks/testvalid.adoc
  .vale/fixtures/AsciiDoc/ClosedIdQuotes/testvalid.adoc
  .vale/fixtures/OpenShiftAsciiDoc/HardWrappedLines/testvalid.adoc
  .vale/fixtures/OpenShiftAsciiDoc/IdHasContextVariable/testvalid.adoc
  .vale/fixtures/OpenShiftAsciiDoc/ModuleContainsContentType/testinvalid.adoc
  .vale/fixtures/OpenShiftAsciiDoc/ModuleContainsContentType/testvalid.adoc
  .vale/fixtures/OpenShiftAsciiDoc/NoTocInModules/testinvalid.adoc
  .vale/fixtures/OpenShiftAsciiDoc/NoTocInModules/testvalid.adoc
  .vale/styles/OpenShiftAsciiDoc/ModuleContainsContentType.yml
  modules/user-guide/pages/openshift-asciidoc-style-for-vale.adoc
Labels: hacktoberfest2023

#678 Enhance Red Hat spelling rule (YAML) to fix false positives on valid words
  .vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
  .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
  .vale/fixtures/RedHat/Spelling/testvalid.adoc
  .vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
  .vale/fixtures/RedHat/TermsWarnings/testvalid.adoc
  .vale/styles/RedHat/CaseSensitiveTerms.yml
  .vale/styles/RedHat/Spelling.yml
  .vale/styles/RedHat/TermsWarnings.yml
Labels: bug, hacktoberfest2023
